import {PaginationOptions} from '../types';

export const DEFAULT_OPTIONS: PaginationOptions = {
  totalNumber: 0,
  pageNumber: 1,
  pageSize: 10,
  pageRange: 2,
  showPrevious: true,
  showNext: true,
  showPageNumbers: true,
  showNavigator: false,
  showGoInput: false,
  showGoButton: false,
  showSizeChanger: false,
  sizeChangerOptions: [10, 20, 50, 100],
  pageLink: '',
  prevText: '&lsaquo;',
  nextText: '&rsaquo;',
  ellipsisText: '...',
  goButtonText: 'Go',
  classPrefix: 'paginationjs',
  activeClassName: 'active',
  disableClassName: 'disabled',
  formatNavigator: 'Total <%= totalNumber %> items',
  formatGoInput: '<%= input %>',
  formatGoButton: '<%= button %>',
  position: 'bottom',
  autoHidePrevious: false,
  autoHideNext: false,
  triggerPagingOnInit: true,
  resetPageNumberOnInit: true,
  hideOnlyOnePage: false,
  hideFirstOnEllipsisShow: false,
  hideLastOnEllipsisShow: false,
  groupItems: false,
  groupClass: 'pagination-group',
  showEllipsis: false
};
