name: Deploy to Distribution Repository

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to distribution repository
        run: |
          # Configurar git para el repo de distribución
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clonar el repo de distribución
          git clone https://x-access-token:${{ secrets.DIST_REPO_TOKEN }}@github.com/NataPeralta/pagination-js.git dist-repo

          # Limpiar y copiar archivos
          cd dist-repo
          rm -rf *
          cp -r ../dist/* .

          # Commit y push
          git add .
          git commit -m "Update distribution files from ${{ github.repository }}@${{ github.sha }}"
          git push origin main
